<?php
/**
 * Template for checkout page
 *
 * @version 20160502
 */
?>
<?php $isActive     = $this->isActive();?>
<?php $isDebug      = $this->getDebugMode();?>
<?php if ($isActive):?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <form class="card-form" method="POST" action="<?php echo Mage::helper('core/url')->getCurrentUrl()?>">
                <input type="hidden" id="cko-kit-card-token" name="payment[checkout_kit_card_token]" value=""/>
                <div class="checkout-kit-card-name-block">
                    <input name="card-name" type="text" placeholder="Name on card"  class="chName input-text required-entry"/>
                </div>
                <div class="checkout-kit-card-block">
                    <input class="input-text cardNumber required-entry validate-cc-number" type="text" placeholder="Credit card number">
                </div>
                <div class="checkout-kit-date-block">
                    <div>
                        <input class="input-text expiryMonth required-entry validate-length maximum-length-2 minimum-length-2 validate-digits" type="text" placeholder="MM" maxlength="2">
                    </div>
                    <div>
                        <input class="input-text expiryYear required-entry validate-length maximum-length-2 minimum-length-2 validate-digits" type="text" placeholder="YY" maxlength="2">
                    </div>
                    <div>
                        <input class="input-text cvv required-entry" type="text" placeholder="CVV">
                    </div>
                </div>
            </form>
            <script>
                window.CKOConfig = {
                    debugMode: '<?php echo $isDebug ? 'true' : 'false'?>',
                    publicKey: '<?php echo $this->getPublicKey()?>',
                    customerEmail: '<?php echo $this->getCustomerEmail();?>',
                    apiError: function (event) {
                        console.log("Error object: %o", event.data);
                    }
                };
            </script>
        </li>
    </ul>
<?php else :?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li><?php echo $this->__('Selected Payment Type is not allowed.') ?></li>
    </ul>
<?php endif?>
