<?php $tokenRersult = $this->getPaymentTokenResult($orderid = null); ?>
<?php if($tokenRersult['succes']): ?>
    <script type="text/javascript">
        var reload = false;
        var loading = false;
        window.CKOConfig = {
            debugMode: true,
            renderMode: 2,
            namespace: 'CheckoutIntegration',
            publicKey: '<?php echo $this->getPublicKey()?>',
            paymentToken: "<?php echo $tokenRersult['token'] ?>",
            value: '<?php echo $this->getConvertAmount() ?>',
            useCurrencyCode: '<?php echo $this->getUseCurrencyCode() ?>',
            currency: '<?php echo $this->getCurrency() ?>',
            customerEmail: '<?php echo $this->getEmailAddress() ?>',
            customerName: '<?php echo $this->getName()?>',
            paymentMode: 'mixed',
            forceMobileRedirect: true,
            title: '<?php echo $this->getStoreName(); ?>',
            subtitle:'<?php echo $this->__('Please enter your credit card details') ?>',
            widgetContainerSelector: '.payment-form',
            styling: {
              logoUrl: '<?php echo $this->getLightBoxUrl() ?>',
              themeColor: '<?php echo $this->getThemeColor() ?>',
              buttonColor: '<?php echo $this->getButtonColor() ?>',
              iconColor: '<?php echo $this->getIconColor() ?>',
            },
            cardCharged: function(event){
                loading = true;
                checkout.setLoadWaiting(false);
                if($buttonCheckout = $$('#checkout-review-submit .btn-checkout')) {

                    var eventClick = $buttonCheckout[0].show().readAttribute('data-clickEvent');
                    document.getElementById('cko-cc-paymenToken').value = event.data.paymentToken;
                    $$('#checkout-review-submit .btn-checkout')[0].writeAttribute('onclick', eventClick);
                    $('review-please-wait').show();
                   fireEvent($$('#checkout-review-submit .btn-checkout')[0], 'click');
                    $$('#checkout-review-submit .btn-checkout')[0].hide();

                    checkout.setLoadWaiting('review');

                }
            },
            paymentTokenExpired: function(){
                reload = true;
                checkout.setLoadWaiting(false);
            },
            lightboxDeactivated: function() {
                checkout.setLoadWaiting(false);
                if(loading){
                   $('review-please-wait').show();
                }
                if(reload) {
                    window.location.reload();
                }
            },       
            cardVerificationRequired : function (event) {
              document.getElementById('cko-3d-redirectUrl').value = event.data.redirectUrl;
              loading = true;
               checkout.setLoadWaiting(false);
                if($buttonCheckout = $$('#checkout-review-submit .btn-checkout')) {

                    var eventClick = $buttonCheckout[0].show().readAttribute('data-clickEvent');
                    document.getElementById('cko-cc-paymenToken').value = event.data.paymentToken;
                    $$('#checkout-review-submit .btn-checkout')[0].writeAttribute('onclick', eventClick);
                    $('review-please-wait').show();
                     
                    fireEvent($$('#checkout-review-submit .btn-checkout')[0], 'click');
                    $$('#checkout-review-submit .btn-checkout')[0].hide();
                    checkout.setLoadWaiting('review');
                    //Checkout.continueFlow();
                }
            },
            ready: function() {
              if(typeof Checkout !='undefined' && Checkout.hasOwnProperty('render') && Checkout.isMobile()) {

                  document.getElementById('cko-redirectUrl').value = Checkout.getRedirectionUrl();
              } else if(typeof CheckoutIntegration !='undefined' && CheckoutIntegration.hasOwnProperty('render') &&  CheckoutIntegration.isMobile()) {

                  document.getElementById('cko-redirectUrl').value = CheckoutIntegration.getRedirectionUrl();

              }
            },
            lpCharged: function(event){
                loading = true;
                checkout.setLoadWaiting(false);
                if($buttonCheckout = $$('#checkout-review-submit .btn-checkout')) {
                    var eventClick = $buttonCheckout[0].show().readAttribute('data-clickEvent');
                    document.getElementById('cko-lp-redirectUrl').value = event.data.redirectUrl;
                    $$('#checkout-review-submit .btn-checkout')[0].writeAttribute('onclick', eventClick);
                    fireEvent($$('#checkout-review-submit .btn-checkout')[0], 'click');
                    $$('#checkout-review-submit .btn-checkout')[0].hide();
                    checkout.setLoadWaiting('review');

                }
                
            },
        };
        if(typeof Checkout!='undefined' && Checkout.hasOwnProperty('render')) {
            Checkout.render(window.CKOConfig);
        }else if(typeof CheckoutIntegration!='undefined' && CheckoutIntegration.hasOwnProperty('render')){
            CheckoutIntegration.render(window.CKOConfig);
        }


    </script>

    <div class="payment-form"></div>

    <?php $_code=$this->getMethodCode() ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
        <li>
            <input type="hidden" name="payment[cko_cc_paymenToken]" id="cko-cc-paymenToken" value="<?php echo
            $this->getPaymentToken() ?>"  class="input-text "/>

            <input type="hidden" name="payment[cko_redirectUrl]" id="cko-redirectUrl" value=""  class="input-text "/>
            <input type="hidden" name="payment[cko_lp_redirectUrl]" id="cko-lp-redirectUrl" value=""  class="input-text "/>
            <input type="hidden" name="payment[cko_3d_redirectUrl]" id="cko-3d-redirectUrl" value=""  class="input-text "/>
        </li>
    </ul>
<?php else:  ?>
    <div style="" id="advice-required-entry-creditcard_cc_token" class="validation-advice">
        <?php echo $this->__($tokenRersult['message']) ?>
    </div>
<?php endif; ?>
