<?php $tokenRersult = $this->getPaymentTokenResult(); ?>
<?php if($tokenRersult['succes']): ?>
    <script type="text/javascript">
        var reload = false;
        window.CKOConfig = {
            debugMode: false,
            renderMode: 2,
            namespace: 'CheckoutIntegration',
            publicKey: '<?php echo $this->getPublicKey()?>',
            paymentToken: "<?php echo $tokenRersult['token'] ?>",
            value: '<?php echo $this->getAmount() ?>',
            currency: '<?php echo $this->getCurrency() ?>',
            customerEmail: '<?php echo $this->getEmailAddress() ?>',
            customerName: '<?php echo $this->getName()?>',
            paymentMode: 'mixed',
            title: '<?php echo $this->getStoreName(); ?>',
            logoUrl: '<?php echo $this->getLightBoxUrl() ?>',
            themeColor: '<?php echo $this->getThemeColor() ?>',
            buttonColor: '<?php echo $this->getButtonColor() ?>',
            iconColor: '<?php echo $this->getIconColor() ?>',
            useCurrencyCode: '<?php echo $this->getUseCurrencyCode() ?>',
            currency: '<?php echo $this->getCurrency() ?>',
            forceMobileRedirect: true,
            subtitle:'<?php echo $this->__('Please enter your credit card details') ?>',
            widgetContainerSelector: '.payment-form',
            cardCharged: function(event){
                document.getElementById('cko-cc-paymenToken').value = event.data.paymentToken;
                fireEvent($('onestepcheckout-place-order'), 'click');


            },
            paymentTokenExpired: function(){
                reload = true;
            },
            lightboxActivated: function() {

                if($('advice-required-bridge-entry-cko-cc-paymenToken')) {
                    $('advice-required-bridge-entry-cko-cc-paymenToken').hide();
                }
            },
            lightboxDeactivated: function() {
                if(reload) {
                    window.location.reload();
                }
            },
            ready: function() {

                if(typeof Checkout !='undefined' && Checkout.hasOwnProperty('render') && Checkout.isMobile()) {

                    document.getElementById('cko-cc-redirectUrl').value = Checkout.getRedirectionUrl();
                }else if(typeof CheckoutIntegration !='undefined' && CheckoutIntegration.hasOwnProperty('render') &&  CheckoutIntegration.isMobile()) {

                    document.getElementById('cko-cc-redirectUrl').value = CheckoutIntegration.getRedirectionUrl();

                }

            }
        };

        if(typeof CheckoutIntegration !='undefined' && CheckoutIntegration.hasOwnProperty('render')) {
            CheckoutIntegration.render(window.CKOConfig);
        }


    </script>

    <div class="payment-form"></div>

    <?php $_code=$this->getMethodCode() ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
        <li>
            <input type="hidden" name="payment[cko_cc_paymenToken]" id="cko-cc-paymenToken" value="-1"  class="input-text required-bridge-entry"/>
            <input type="hidden" name="payment[cko_cc_redirectUrl]" id="cko-cc-redirectUrl" value=""  class="input-text "/>
        </li>
    </ul>
<?php else:  ?>
    <div style="" id="advice-required-entry-creditcard_cc_token" class="validation-advice">
        <?php echo $this->__($tokenRersult['message']) ?>
    </div>
<?php endif; ?>
<script type="text/javascript">

    Validation.add('required-bridge-entry' ,'<?php echo $this->__("Please wait while we load you secure form") ?>', function(value){
        var form = new VarienForm('onestepcheckout-form'),
            useTitles = form.validator.options.useTitles,
            callback = form.validator.options.onElementValidate,
            result = true;
        Form.getElements(form.form).collect(function(elm) {
            if (elm.hasClassName('local-validation') && !this.isElementInForm(elm, this.form)) {
                return true;
            }
            if(elm.id!='cko-cc-paymenToken') {

                if (!Validation.validate(elm, {useTitle: useTitles, onElementValidate: callback})) {

                    result = false;
                }
            }
        });


        if($$('[name="payment\[method\]"]:checked')[0].id=='p_method_creditcard' && value==-1  && result) {
            CheckoutIntegration.configure(window.CKOConfig);
            if( !CheckoutIntegration.isMobile()) {
                CheckoutIntegration.open();
            }else {
                return true;
            }
        }else {
            return true;
        }
        return value==-1?false:true;
    });
</script>

